kind: pipeline
name: drone-lambda-plugin

workspace:
  base: /go
  path: src/github.com/scnace/drone-lambda-plugin

steps:
  - name: build
    image: golang:1.13
    environment:
    commands:
      - go test ./...
      - go install

  - name: push_dockerhub
    image: plugins/docker
    settings:
      repo: scnace/drone-lambda-plugin
      auto_tag: true
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASSWORD
      dockerfile: Dockerfile
    when:
      event:
      - push
      branch:
      - master
