workspace:
  base: /go
  path: src/github.com/omerxx/drone-lambda-plugin

pipeline:
  build:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make build
      - make test

  docker:
    image: omerxx/docker-lambda-plugin
    email: omerxx@gmail.com
    tags: latest
    secrets: [ docker_username, docker_password ]
