pipeline:
  image: golang:1.8
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

  docker:
    image: omerxx/docker-lambda-plugin
    email: omerxx@gmail.com
    tags: latest
    secrets: [ docker_username, docker_password ]
