workspace:
  base: /go
  path: src/github.com/scnace/drone-lambda-plugin

pipeline:
  build:
    image: golang:1.13
    environment:
    commands:
      - go test ./...
      - go install

  docker:
    image: plugins/docker
    settings:
      repo: scnace/drone-lambda-plugin
      autotag: true
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASSWORD
      dockerfile: Dockerfile
    when:
      event:
      - push
      branch:
      - master
